permissions:
  contents: read  
  
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  init:
    name: CI Workflow
    uses: codeparce/ci-workflows/.github/workflows/init.yml@v1
    with:
      type: front
      cloud: azure
      services: swa
    secrets: inherit
      