permissions:
  contents: read  
  
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  init:
    name: CI Workflow
    uses: codeparce/ci-workflows/.github/workflows/pipelines/node-init.yml@v1
    with:
      node-version: 24
    secrets: inherit
      